version: "3"

services:
  db:
    image: neo4j:4.1
    ports:
      - "7474:7474" # http
      - "7687:7687" # bolt
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - "callflow_db:/data"

volumes:
  callflow_db: